### ISSUE TITLE
Error saving fields.yaml because of jsonable is null

### ISSUE THREAD

**Issue by NecroMan** [wintercms/wn-builder-plugin#38] opened 2022-04-29 00:27 UTC
There is an error when saving fields.yaml from editor. The Model was generated by Builder plugin and has no `$jsonable` property.

![2022-04-29 03_22_59-ItemArticle_fields _ Builder _ Winter CMS](https://user-images.githubusercontent.com/488178/165867927-2ee6443a-c74d-4c32-94f6-36a90489c590.png)

This could be fixed with adding an `(array)` type cast like here:

![2022-04-29 03_25_09-rsv-led_october – IndexModelFormOperations php](https://user-images.githubusercontent.com/488178/165868080-9b569286-f34b-48cf-a567-ee2e8a69a705.png)

**Comment by bennothommo** [comment] 2022-04-29 04:43
Duplicate of #31. This has been fixed as of https://github.com/wintercms/wn-builder-plugin/commit/6946a6eecc65d80bf58bead2f7a8aa08ba0ed922. It should be out in the next few days as a new release of the Builder plugin.

**Closed** 2022-04-29 04:43 UTC
Labels: duplicate
