### ISSUE TITLE
"Undefined array key "multiple"" on line 103 of /application/plugins/winter/builder/classes/ModelFormModel.php

### ISSUE THREAD

**Issue by pavelmgn** [wintercms/wn-builder-plugin#43] opened 2022-08-17 04:26 UTC
After save dropdown in form builder this error.

![image](https://user-images.githubusercontent.com/8817759/185034333-e3071823-fae5-4587-a6e7-2981f8da3466.png)

![image](https://user-images.githubusercontent.com/8817759/185034480-af59caa4-2ec2-49fa-8816-30a7ebf8c960.png)

multiple not exists =)

```
^ array:4 [
  "label" => "Тип"
  "showSearch" => true
  "span" => "auto"
  "type" => "dropdown"
]
```

**Comment by LukeTowers** [comment] 2022-08-17 05:08
This was fixed in https://github.com/wintercms/wn-builder-plugin/commit/36075870087aef719ccfa394c1d603ed8a9b2665, load this plugin via composer targeting `dev-main` as your desired version for now and perhaps @bennothommo can fix the test suite and push a new version when he has a moment.

**Comment by LukeTowers** [comment] 2022-08-17 05:09
Duplicate of #33

**Closed by LukeTowers** 2022-08-17 05:08 UTC

**Comment by pavelmgn** [comment] 2022-08-17 08:38
thanks =)
